### ISSUE TITLE
could you guide the latest installation??

### ISSUE THREAD

**Issue by chrisjin2** [tencent-ailab/hok_env#26]
HI, tencent AIlab

Thanks for providing a wonderful simulator hok_env.
I tried to install a simulation. however, I could not follow installation step by step through the documentation.

How to install on win10.
'pip install -e' not working on WSL2. I could not find 'ai_simulator_remote' folder and sgame_simulator.common.conf file.

please, help for me.

**Comment by hongyangqin** [comment]
Sorry about the bad experience. The new documentation is on the plan. 

---

1. Try to use `pip install hok` to install the `hok_env`
2. No need to add `ai_simulator_remote` to PATH anymore. Here we use the ` set PATH=%PATH%;..\lib\` to set the PATH
3. The content of `sgame_simulator.common.conf` is shown in the `readme.md`.

```
{
    "abs_file": "../scene/1V1.abs",
    "core_assets": "../core_assets",
    "game_id": "kaiwu-base-35401-35400-6842-1669963820108111766-217",
    "hero_conf": [
        {
            "hero_id": 199
        },
        {
            "hero_id": 199
        }
    ]
}
```

See also:
https://github.com/tencent-ailab/hok_env/issues/17#issue-1535700020
https://github.com/tencent-ailab/hok_env/issues/18#issue-1535719826

**Comment by arnoli777** [comment]
HI tencent AIlab！

Thank you very much for your contribution to this interesting project.

But I encountered some problems during the installation process.

When I use the cygwin1.dll provided by you, I will be prompted that following error:
`his problem is probably due to using incompatible versions of the cygwin DLL,` 

 Then I try to install a cygwin64 on my computer and keep the latest version of cygwin1.dll. Then execute the command `./sgame_simulator_remote_zmq.exe ./sgame_simulator.common.conf,` and the didn't see anything in the git terminal. 

and I execute the command `./sgame_simulator_remote_zmq.exe ./sgame_simulator.common.conf,`  in the cygwin64 terminal. 
I see the error is ` *** fatal error - couldn't create signal pipe, Win32 error 5` . 

I guess it should be the version of cygwin1.dll. However, I used the cygwin1.dll provided by you and the installed cygwin1.dll with errors and could not start the gamecore correctly. 

Please help me solve this problem. Thank you.
